import { ICar } from "./types";

export const mockCars: ICar[] = [
  {
    car_id: 1,
    make: "Toyota",
    model: "Camry",
    year: 2022,
    price: 25000,
    mileage: 15000,
    color: "Silver",
    body_type: "Sedan",
    fuel_type: "Gasoline",
    transmission: "Automatic",
    engine: {
      displacement: 2000,
      cylinders: 4,
    },
    description: "A reliable sedan with good fuel efficiency.",
    image_urls: [
      "https://example.com/car1_image1.jpg",
      "https://example.com/car1_image2.jpg",
    ],
    seller_id: 1,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    car_id: 2,
    make: "Honda",
    model: "Civic",
    year: 2021,
    price: 22000,
    mileage: 12000,
    color: "Blue",
    body_type: "Sedan",
    fuel_type: "Gasoline",
    transmission: "Automatic",
    engine: {
      displacement: 1800,
      cylinders: 4,
    },
    description: "A compact sedan with great fuel economy.",
    image_urls: [
      "https://example.com/car2_image1.jpg",
      "https://example.com/car2_image2.jpg",
    ],
    seller_id: 2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    car_id: 3,
    make: "Ford",
    model: "F-150",
    year: 2023,
    price: 35000,
    mileage: 8000,
    color: "Red",
    body_type: "Truck",
    fuel_type: "Gasoline",
    transmission: "Automatic",
    engine: {
      displacement: 3500,
      cylinders: 6,
    },
    description: "A powerful pickup truck for tough jobs.",
    image_urls: [
      "https://example.com/car3_image1.jpg",
      "https://example.com/car3_image2.jpg",
    ],
    seller_id: 3,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    car_id: 4,
    make: "Nissan",
    model: "Altima",
    year: 2020,
    price: 18000,
    mileage: 20000,
    color: "Black",
    body_type: "Sedan",
    fuel_type: "Gasoline",
    transmission: "CVT",
    engine: {
      displacement: 2500,
      cylinders: 4,
    },
    description: "A comfortable and efficient family sedan.",
    image_urls: [
      "https://example.com/car4_image1.jpg",
      "https://example.com/car4_image2.jpg",
    ],
    seller_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    car_id: 5,
    make: "Chevrolet",
    model: "Silverado",
    year: 2022,
    price: 38000,
    mileage: 10000,
    color: "White",
    body_type: "Truck",
    fuel_type: "Gasoline",
    transmission: "Automatic",
    engine: {
      displacement: 5000,
      cylinders: 8,
    },
    description: "A rugged and spacious pickup truck.",
    image_urls: [
      "https://example.com/car5_image1.jpg",
      "https://example.com/car5_image2.jpg",
    ],
    seller_id: 5,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    car_id: 6,
    make: "Hyundai",
    model: "Elantra",
    year: 2021,
    price: 19000,
    mileage: 15000,
    color: "Gray",
    body_type: "Sedan",
    fuel_type: "Gasoline",
    transmission: "Automatic",
    engine: {
      displacement: 2000,
      cylinders: 4,
    },
    description: "A stylish and affordable compact sedan.",
    image_urls: [
      "https://example.com/car6_image1.jpg",
      "https://example.com/car6_image2.jpg",
    ],
    seller_id: 6,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    car_id: 7,
    make: "Jeep",
    model: "Wrangler",
    year: 2023,
    price: 42000,
    mileage: 5000,
    color: "Green",
    body_type: "SUV",
    fuel_type: "Gasoline",
    transmission: "Manual",
    engine: {
      displacement: 3600,
      cylinders: 6,
    },
    description: "An off-road enthusiast's dream SUV.",
    image_urls: [
      "https://example.com/car7_image1.jpg",
      "https://example.com/car7_image2.jpg",
    ],
    seller_id: 7,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    car_id: 8,
    make: "Kia",
    model: "Sportage",
    year: 2022,
    price: 24000,
    mileage: 16000,
    color: "Silver",
    body_type: "SUV",
    fuel_type: "Gasoline",
    transmission: "Automatic",
    engine: {
      displacement: 2200,
      cylinders: 4,
    },
    description: "A versatile and comfortable compact SUV.",
    image_urls: [
      "https://example.com/car8_image1.jpg",
      "https://example.com/car8_image2.jpg",
    ],
    seller_id: 8,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    car_id: 9,
    make: "BMW",
    model: "3 Series",
    year: 2023,
    price: 48000,
    mileage: 6000,
    color: "Black",
    body_type: "Sedan",
    fuel_type: "Gasoline",
    transmission: "Automatic",
    engine: {
      displacement: 3000,
      cylinders: 6,
    },
    description: "A luxury sedan with sporty performance.",
    image_urls: [
      "https://example.com/car9_image1.jpg",
      "https://example.com/car9_image2.jpg",
    ],
    seller_id: 9,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    car_id: 10,
    make: "Mercedes-Benz",
    model: "GLC",
    year: 2022,
    price: 55000,
    mileage: 9000,
    color: "Silver",
    body_type: "SUV",
    fuel_type: "Gasoline",
    transmission: "Automatic",
    engine: {
      displacement: 2500,
      cylinders: 4,
    },
    description: "A premium SUV with advanced features.",
    image_urls: [
      "https://example.com/car10_image1.jpg",
      "https://example.com/car10_image2.jpg",
    ],
    seller_id: 10,
    created_at: new Date(),
    updated_at: new Date(),
  },
];
// Add
